
package com.soap.ws.jaxb;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductInterface", targetNamespace = "http://jaxb.soap.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductInterface {


    /**
     * 
     * @return
     *     returns com.soap.ws.jaxb.Product
     */
    @WebMethod
    @WebResult(name = "Product", partName = "Product")
    @Action(input = "http://jaxb.soap.com/ProductInterface/getProductRequest", output = "http://jaxb.soap.com/ProductInterface/getProductResponse")
    public Product getProduct();

}
